USE [master]
GO

/****** Object:  Database [sat_grocery_shop]    Script Date: 2/15/2026 5:24:29 PM ******/
CREATE DATABASE [sat_grocery_shop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sat_grocery_shop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\sat_grocery_shop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'sat_grocery_shop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\sat_grocery_shop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sat_grocery_shop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [sat_grocery_shop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sat_grocery_shop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sat_grocery_shop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sat_grocery_shop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sat_grocery_shop] SET ARITHABORT OFF 
GO

ALTER DATABASE [sat_grocery_shop] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [sat_grocery_shop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sat_grocery_shop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sat_grocery_shop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sat_grocery_shop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sat_grocery_shop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sat_grocery_shop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sat_grocery_shop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sat_grocery_shop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sat_grocery_shop] SET  ENABLE_BROKER 
GO

ALTER DATABASE [sat_grocery_shop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sat_grocery_shop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sat_grocery_shop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sat_grocery_shop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sat_grocery_shop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sat_grocery_shop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [sat_grocery_shop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sat_grocery_shop] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [sat_grocery_shop] SET  MULTI_USER 
GO

ALTER DATABASE [sat_grocery_shop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [sat_grocery_shop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [sat_grocery_shop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [sat_grocery_shop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [sat_grocery_shop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [sat_grocery_shop] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [sat_grocery_shop] SET QUERY_STORE = ON
GO

ALTER DATABASE [sat_grocery_shop] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [sat_grocery_shop] SET  READ_WRITE 
GO


